// Remotion fragments backend: one shared workspace (~/kadr-fragments) holds
// every fragment composition as a small TSX module. A vite dev server gives
// the editor's preview a live, hot-reloading Player page (no renders during
// iteration); `remotion render` runs exactly once per fragment content hash
// at export time.
import { app, ipcMain, BrowserWindow } from 'electron'
import { spawn, execFileSync, ChildProcess } from 'child_process'
import { promises as fs, existsSync, readdirSync, statSync, readFileSync, realpathSync } from 'fs'
import { join, basename, dirname } from 'path'
import { createHash } from 'crypto'
import { homedir, tmpdir } from 'os'
import { connect } from 'net'
import type { FragmentSpec, FragmentInfo } from '@shared/types'
// files Kadr keeps in the workspace's src/_kadr (see electron/fragment-kit)
import VITE_CONFIG from './fragment-kit/vite.config.ts?raw'
import PLAYER_TSX from './fragment-kit/player.tsx?raw'
import THREE_PREVIEW_TSX from './fragment-kit/three-preview.tsx?raw'
import RUNTIME_TS from './fragment-kit/runtime.ts?raw'
import WEBPACK_TS from './fragment-kit/webpack.ts?raw'
import ASSETS_D_TS from './fragment-kit/assets.d.ts?raw'
import KIT_THREE_TSX from './fragment-kit/three.tsx?raw'

export const WORKSPACE = process.env.KADR_FRAGMENTS_DIR || join(homedir(), 'kadr-fragments')
const FRAG_DIR = () => join(WORKSPACE, 'src', 'fragments')
const PROJECTS_DIR = () => join(WORKSPACE, 'src', '_projects')
const KADR_DIR = () => join(WORKSPACE, 'src', '_kadr')

/** A saved project's folder in the workspace (src/_projects/<key>):
    readable, and unique per project path. */
export function projectKey(projectDir: string): string {
  const name = basename(projectDir).normalize('NFKD').replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 24)
  return `${name || 'project'}-${createHash('sha1').update(projectDir).digest('hex').slice(0, 8)}`
}

/** The project a fragment belongs to (its sources live in
    <project>/kadr-fragments/<id>), or null for a workspace-only fragment. */
async function projectDirOf(id: string): Promise<string | null> {
  try {
    const real = await fs.realpath(join(FRAG_DIR(), id))
    return basename(dirname(real)) === 'kadr-fragments' ? dirname(dirname(real)) : null
  } catch {
    return null
  }
}

/**
 * <project>/kadr-lib — the project's shared code, models, fonts and media,
 * imported from any of its fragments as '@lib/…' (no copies per fragment:
 * one project had eight identical copies of its 50 KB film module and of
 * megabytes of model data, kept in step by a shell script). The workspace
 * reaches it through the link src/_projects/<key>/lib, so bare imports inside
 * it (three, react) resolve from the workspace's node_modules like any
 * fragment's. fonts.ts registers kadr-lib/fonts for the preview page.
 */
async function ensureProjectLib(projectDir: string): Promise<string> {
  const lib = join(projectDir, 'kadr-lib')
  await fs.mkdir(lib, { recursive: true })
  const key = projectKey(projectDir)
  const home = join(PROJECTS_DIR(), key)
  await fs.mkdir(home, { recursive: true })
  const link = join(home, 'lib')
  const cur = await fs.readlink(link).catch(() => null)
  if (cur !== lib) {
    await fs.rm(link, { force: true }).catch(() => { /* nothing there */ })
    await fs.symlink(lib, link, linkType)
  }
  await writeManaged(join(home, 'fonts.ts'),
    `// AUTO-GENERATED by Kadr — registers the fonts in kadr-lib/fonts for the preview page.\n` +
    `import 'virtual:kadr-fonts/${key}'\n`)
  return key
}

// npm install and remotion's headless-chrome download may need the user's
// network settings (proxies etc.) — shared with the Claude session config:
// userData/claude-env.json { "env": { "HTTPS_PROXY": "...", ... } }
async function netEnv(): Promise<Record<string, string>> {
  try {
    const p = join(app.getPath('userData'), 'claude-env.json')
    const cfg = JSON.parse(await fs.readFile(p, 'utf8'))
    return cfg?.env ?? {}
  } catch {
    return {}
  }
}

// ------------------------------------------------------------- scaffolding

// What the workspace needs. Old workspaces are brought up to this list in
// place (migrateWorkspace) — package.json used to be written only when it was
// missing, so a dependency added later never reached an existing install and
// the three.js packages had to be added by hand.
const WS_DEPS: Record<string, string> = {
  '@react-three/fiber': '8.17.14',
  '@remotion/cli': '4.0.247',
  '@remotion/player': '4.0.247',
  '@remotion/three': '4.0.247',
  react: '18.3.1',
  'react-dom': '18.3.1',
  remotion: '4.0.247',
  three: '0.170.0',
  // mesh intersection tests for the 3D kit's collision check
  'three-mesh-bvh': '0.8.3'
}
const WS_DEV_DEPS: Record<string, string> = {
  '@types/react': '18.3.3',
  // three ships no types: without these every r3f material in a fragment
  // was a false type error
  '@types/three': '0.170.0',
  '@vitejs/plugin-react': '4.3.1',
  typescript: '5.5.4',
  vite: '5.4.8'
}
const PKG_JSON = JSON.stringify({
  name: 'kadr-fragments',
  private: true,
  description: 'Kadr video editor: Remotion fragment compositions (managed; src/fragments/* are yours)',
  dependencies: WS_DEPS,
  devDependencies: WS_DEV_DEPS
}, null, 2) + '\n'

const TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "jsx": "react-jsx",
    "strict": false,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "noEmit": true,
    "baseUrl": ".",
    "paths": { "@kadr/*": ["src/_kadr/*"] }
  },
  "include": ["src", "player.tsx"]
}
`

const INDEX_HTML = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>
      html, body { margin: 0; padding: 0; background: transparent; overflow: hidden; }
      #root { width: 100vw; height: 100vh; }
    </style>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/player.tsx"></script>
  </body>
</html>
`

const ROOT_TSX = `// Compositions for \`remotion render\` — derived from the registry.
// Managed by Kadr — do not edit.
import React from 'react'
import { Composition } from 'remotion'
import { fragments } from './fragments'

export const Root: React.FC = () => (
  <>
    {Object.entries(fragments).map(([id, f]) => (
      <Composition
        key={id}
        id={id}
        component={f.component as React.FC}
        durationInFrames={f.meta.durationInFrames}
        fps={f.meta.fps}
        width={f.meta.width}
        height={f.meta.height}
      />
    ))}
  </>
)
`

const INDEX_TS = `import { registerRoot } from 'remotion'
import { Root } from './Root'
registerRoot(Root)
`

const fragmentTemplate = (name: string) => `import React from 'react'
import { AbsoluteFill, useCurrentFrame, useVideoConfig, interpolate, spring } from 'remotion'
import meta from './meta.json'

// «${name}» — Kadr fragment. Edit freely: the editor preview hot-reloads.
// meta.json (width/height/fps/durationInFrames) is the single source of
// truth for timing; keep it in sync if you change the duration.

const Frag: React.FC = () => {
  const frame = useCurrentFrame()
  const { fps, durationInFrames } = useVideoConfig()
  const appear = spring({ frame, fps, config: { damping: 14 } })
  const fade = interpolate(frame, [durationInFrames - Math.min(20, durationInFrames / 4), durationInFrames], [1, 0], {
    extrapolateLeft: 'clamp', extrapolateRight: 'clamp'
  })
  return (
    <AbsoluteFill style={{ justifyContent: 'center', alignItems: 'center', opacity: fade }}>
      <div
        style={{
          fontFamily: 'sans-serif',
          fontSize: 90,
          fontWeight: 700,
          color: 'white',
          textShadow: '0 4px 30px rgba(0,0,0,0.6)',
          transform: \`scale(\${appear})\`
        }}
      >
        ${name}
      </div>
    </AbsoluteFill>
  )
}

export const fragment = { component: Frag, meta }
`

async function writeIfMissing(path: string, content: string) {
  try {
    await fs.access(path)
  } catch {
    await fs.writeFile(path, content)
  }
}

/** Kadr-managed file ("do not edit"): follow template changes in place.
    Written to a sidecar and renamed: the dev server must never see a
    truncated file (a plain writeFile is a truncate and then a write — two
    change events, and a request between them compiles the empty one). */
async function writeManaged(path: string, content: string) {
  try {
    if ((await fs.readFile(path, 'utf8')) === content) return
  } catch { /* missing */ }
  const tmp = `${path}.part-${process.pid}`
  await fs.writeFile(tmp, content)
  await fs.rename(tmp, path)
}

/** Rewrite the registry from the folders actually present on disk.
    Project-owned fragments appear here as symlinks — include them too
    (a symlinked Dirent is never isDirectory(); existsSync follows it).
    Two files: index.ts imports everything (remotion's Root), lazy.ts maps
    ids to dynamic imports (the preview's player page — one fragment each).
    Written only when the content changes: every rewrite is a file change the
    dev server reacts to. */
async function regenRegistry() {
  const dirs = (await fs.readdir(FRAG_DIR(), { withFileTypes: true }))
    .filter((d) => d.isDirectory() || d.isSymbolicLink())
    .map((d) => d.name)
    .filter((n) => existsSync(join(FRAG_DIR(), n, 'index.tsx')))
    .sort()
  const head = '// AUTO-GENERATED by Kadr — fragment registry. Do not edit.'
  await writeManaged(join(FRAG_DIR(), 'index.ts'), [
    head,
    ...dirs.map((d, i) => `import { fragment as f${i} } from './${d}'`),
    '',
    'export const fragments = {',
    ...dirs.map((d, i) => `  '${d}': f${i},`),
    '}',
    ''
  ].join('\n'))
  // a project's fonts register BEFORE its fragment module runs
  const loader = async (d: string) => {
    const pd = await projectDirOf(d)
    const key = pd ? projectKey(pd) : null
    return key && existsSync(join(PROJECTS_DIR(), key, 'fonts.ts'))
      ? `  '${d}': () => import('../_projects/${key}/fonts').then(() => import('./${d}')),`
      : `  '${d}': () => import('./${d}'),`
  }
  await writeManaged(join(FRAG_DIR(), 'lazy.ts'), [
    head,
    'export const loaders: Record<string, () => Promise<{ fragment: any }>> = {',
    ...(await Promise.all(dirs.map(loader))),
    '}',
    ''
  ].join('\n'))
}

/** Bring an existing workspace up to WS_DEPS / TSCONFIG in place; true when
    some declared package is not installed yet. Only ADDS: a version the
    user pinned, a dependency of their own, an option they set are kept. */
async function migrateWorkspace(): Promise<boolean> {
  const pkgPath = join(WORKSPACE, 'package.json')
  try {
    const pkg = JSON.parse(await fs.readFile(pkgPath, 'utf8'))
    let changed = false
    const has = (n: string) => !!(pkg.dependencies?.[n] || pkg.devDependencies?.[n])
    for (const [n, v] of Object.entries(WS_DEPS)) if (!has(n)) { (pkg.dependencies ??= {})[n] = v; changed = true }
    for (const [n, v] of Object.entries(WS_DEV_DEPS)) if (!has(n)) { (pkg.devDependencies ??= {})[n] = v; changed = true }
    if (changed) await fs.writeFile(pkgPath, JSON.stringify(pkg, null, 2) + '\n')
  } catch { /* unreadable package.json: npm install will say so */ }
  const tsPath = join(WORKSPACE, 'tsconfig.json')
  try {
    const ts = JSON.parse(await fs.readFile(tsPath, 'utf8'))
    const co = (ts.compilerOptions ??= {})
    let changed = false
    if (!co.baseUrl) { co.baseUrl = '.'; changed = true }
    if (!co.paths?.['@kadr/*']) { co.paths = { ...(co.paths ?? {}), '@kadr/*': ['src/_kadr/*'] }; changed = true }
    if (changed) await fs.writeFile(tsPath, JSON.stringify(ts, null, 2) + '\n')
  } catch { /* hand-edited with comments: leave it alone */ }
  return [...Object.keys(WS_DEPS), ...Object.keys(WS_DEV_DEPS)]
    .some((n) => !existsSync(join(WORKSPACE, 'node_modules', n, 'package.json')))
}

/**
 * src/_projects/<key>/ of projects that are gone (deleted, or a /tmp test
 * project): their lib link dangles. Nothing else refers to them, and opening
 * the project again recreates the folder (ensureProjectLib), so a dangling
 * one is removed — before this they piled up, one per project ever saved.
 * Only folders whose lib is a DANGLING SYMLINK are touched.
 */
let prunedProjects = false
async function pruneProjectLinks(): Promise<void> {
  if (prunedProjects) return
  prunedProjects = true
  let keys: string[] = []
  try { keys = await fs.readdir(PROJECTS_DIR()) } catch { return }
  for (const key of keys) {
    const link = join(PROJECTS_DIR(), key, 'lib')
    const st = await fs.lstat(link).catch(() => null)
    if (!st?.isSymbolicLink()) continue
    if (await fs.stat(link).then(() => true, () => false)) continue // target still there
    await fs.rm(join(PROJECTS_DIR(), key), { recursive: true, force: true }).catch(() => {})
  }
}

async function ensureWorkspace(
  onProgress?: (phase: string, p: number) => void
): Promise<{ dir: string; installed: boolean }> {
  await fs.mkdir(FRAG_DIR(), { recursive: true })
  await pruneProjectLinks()
  await writeIfMissing(join(WORKSPACE, 'package.json'), PKG_JSON)
  await writeManaged(join(WORKSPACE, 'vite.config.ts'), VITE_CONFIG)
  await writeIfMissing(join(WORKSPACE, 'tsconfig.json'), TSCONFIG)
  await writeIfMissing(join(WORKSPACE, 'index.html'), INDEX_HTML)
  // the registry first: the player page imports lazy.ts
  if (!existsSync(join(FRAG_DIR(), 'index.ts')) || !existsSync(join(FRAG_DIR(), 'lazy.ts'))) await regenRegistry()
  await writeManaged(join(WORKSPACE, 'player.tsx'), PLAYER_TSX)
  await writeManaged(join(WORKSPACE, 'src', 'Root.tsx'), ROOT_TSX)
  await fs.mkdir(KADR_DIR(), { recursive: true })
  await writeManaged(join(KADR_DIR(), 'three-preview.tsx'), THREE_PREVIEW_TSX)
  await writeManaged(join(KADR_DIR(), 'runtime.ts'), RUNTIME_TS)
  await writeManaged(join(KADR_DIR(), 'webpack.ts'), WEBPACK_TS)
  await writeManaged(join(KADR_DIR(), 'assets.d.ts'), ASSETS_D_TS)
  await writeManaged(join(KADR_DIR(), 'three.tsx'), KIT_THREE_TSX)
  await writeIfMissing(join(WORKSPACE, 'src', 'index.ts'), INDEX_TS)

  const needInstall = await migrateWorkspace()
  let installed = false
  if (needInstall) {
    onProgress?.('install', 0)
    const extraEnv = await netEnv()
    await new Promise<void>((resolve, reject) => {
      const child = spawn('npm', ['install', '--no-audit', '--no-fund'], {
        cwd: WORKSPACE,
        env: { ...process.env, ...extraEnv },
        stdio: ['ignore', 'pipe', 'pipe']
      })
      let err = ''
      child.stderr.on('data', (c) => { err += c })
      child.on('error', reject)
      child.on('close', (code) => {
        if (code === 0) resolve()
        else reject(new Error(`npm install failed (${code}): ${err.slice(-600)}`))
      })
    })
    installed = true
    onProgress?.('install', 1)
  }
  return { dir: WORKSPACE, installed }
}

// --------------------------------------------------------------- dev server

let server: { child: ChildProcess | null; url: string } | null = null
// overridable so a second, isolated instance (test bench) never shares — and
// never restarts — the working editor's server
const VITE_PORT = Number(process.env.KADR_FRAGMENTS_PORT) || 5621

/** A server (possibly from a previous app run) already serving the page? */
async function probeExisting(): Promise<string | null> {
  try {
    const res = await fetch(`http://127.0.0.1:${VITE_PORT}/`, {
      signal: AbortSignal.timeout(1500)
    })
    const body = await res.text()
    if (res.ok && body.includes('player.tsx')) return `http://127.0.0.1:${VITE_PORT}`
  } catch { /* nothing there */ }
  return null
}

/** something accepts connections on the port (a server, maybe not answering yet) */
const portTaken = () => new Promise<boolean>((resolve) => {
  const sock = connect({ host: '127.0.0.1', port: VITE_PORT })
  const done = (v: boolean) => { sock.destroy(); resolve(v) }
  sock.once('connect', () => done(true))
  sock.once('error', () => done(false))
  sock.setTimeout(1000, () => done(false))
})

/**
 * The server of an earlier run, waited for while it RESTARTS. ensureWorkspace
 * rewrites vite.config.ts when Kadr's template changed, and a running vite
 * restarts itself on that — for a few seconds its port is taken but nothing
 * answers. Probing once then started a second vite, which died on «Port 5621
 * is already in use», and the preview showed that error instead of the
 * fragments (met right after an update of the template).
 */
async function awaitExisting(ms: number): Promise<string | null> {
  const until = Date.now() + ms
  for (;;) {
    const url = await probeExisting()
    if (url) return url
    if (Date.now() > until || !(await portTaken())) return null
    await new Promise((r) => setTimeout(r, 400))
  }
}

let starting: Promise<{ url: string }> | null = null

async function ensureServer(): Promise<{ url: string }> {
  if (server && (!server.child || server.child.exitCode === null)) return { url: server.url }
  // one start at a time: two callers at once used to spawn two servers
  starting ??= startServer().finally(() => { starting = null })
  return starting
}

async function startServer(): Promise<{ url: string }> {
  server = null
  await ensureWorkspace()
  const existing = await awaitExisting(20000)
  if (existing) {
    server = { child: null, url: existing }
    return { url: existing }
  }
  // a watchdog shell kills vite when this process dies — orphaned children
  // inherit Electron's listening sockets and would block the next launch.
  // The bin runs directly (NOT via npx — npx makes vite a grandchild the
  // watchdog's kill couldn't reach).
  const child = spawn('sh', ['-c',
    `"./node_modules/.bin/vite" --port ${VITE_PORT} --strictPort & V=$!; ` +
    `(while kill -0 ${process.pid} 2>/dev/null; do sleep 3; done; kill $V 2>/dev/null) & ` +
    'wait $V'
  ], {
    cwd: WORKSPACE,
    env: { ...process.env },
    stdio: ['ignore', 'pipe', 'pipe']
  })
  let adopted = false
  const url = await new Promise<string>((resolve, reject) => {
    let out = ''
    const timer = setTimeout(() => reject(new Error('vite start timeout: ' + out.slice(-400))), 30000)
    const onData = (c: Buffer) => {
      out += c
      // vite's banner carries ANSI colors that split the port digits
      // ("http://127.0.0.1:\x1b[1m5621") — strip them before matching, or a
      // cold start never resolves and every first fragment use flakes
      const clean = out.replace(/\x1b\[[0-9;]*m/g, '')
      const m = clean.match(/(http:\/\/127\.0\.0\.1:\d+)/)
      if (m) {
        clearTimeout(timer)
        resolve(m[1])
      }
    }
    child.stdout!.on('data', onData)
    child.stderr!.on('data', onData)
    child.on('error', (e) => { clearTimeout(timer); reject(e) })
    child.on('close', (code) => { clearTimeout(timer); reject(new Error(`vite exited ${code}: ${out.slice(-400)}`)) })
  }).catch(async (e) => {
    // lost a race for the port to a server that came up meanwhile: use that one
    const other = /already in use/i.test(String(e?.message)) ? await awaitExisting(15000) : null
    if (!other) throw e
    adopted = true
    return other
  })
  server = { child: adopted ? null : child, url }
  return { url }
}

function stopServer() {
  server?.child?.kill()
  server = null
}

// ------------------------------------------------------------ create/render

const slug = (s: string) =>
  s.normalize('NFKD').replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 24) || 'frag'

/** The per-project home of fragment sources: <projectDir>/kadr-fragments. */
const projectFragHome = (projectDir: string) => join(projectDir, 'kadr-fragments')

const linkType = process.platform === 'win32' ? 'junction' : 'dir'

const assertId = (id: string) => {
  if (!id || id.includes('/') || id.includes('\\') || id.includes('..')) {
    throw new Error('bad fragment id')
  }
}

async function createFragment(spec: FragmentSpec, projectDir?: string | null): Promise<FragmentInfo> {
  await ensureWorkspace()
  const id = `${slug(spec.name)}-${Math.random().toString(36).slice(2, 7)}`
  const link = join(FRAG_DIR(), id)
  let dir = link
  if (projectDir) {
    // the source of truth lives next to the .kadr file — easy to find, moves
    // with the project; the workspace only holds a symlink so vite/remotion
    // keep seeing it under src/fragments
    dir = join(projectFragHome(projectDir), id)
    await fs.mkdir(dir, { recursive: true })
    await fs.symlink(dir, link, linkType)
    await ensureProjectLib(projectDir)
  } else {
    await fs.mkdir(dir, { recursive: true })
  }
  const meta = {
    id,
    name: spec.name,
    width: Math.round(spec.width),
    height: Math.round(spec.height),
    fps: Math.max(60, Math.round(spec.fps)),
    durationInFrames: Math.max(1, Math.round(spec.durationInFrames)),
    transparent: !!spec.transparent
  }
  await fs.writeFile(join(dir, 'meta.json'), JSON.stringify(meta, null, 2))
  await fs.writeFile(join(dir, 'index.tsx'), fragmentTemplate(spec.name))
  await regenRegistry()
  return { id, dir, entry: join(dir, 'index.tsx'), meta: meta as unknown as FragmentSpec }
}

async function deleteFragment(id: string): Promise<void> {
  assertId(id)
  const link = join(FRAG_DIR(), id)
  // a project-owned fragment: the workspace entry is a symlink — remove the
  // real folder too (but only ever inside a kadr-fragments home)
  try {
    const st = await fs.lstat(link)
    if (st.isSymbolicLink()) {
      const real = await fs.realpath(link).catch(() => null)
      if (real && basename(dirname(real)) === 'kadr-fragments') {
        await fs.rm(real, { recursive: true, force: true })
      }
    }
  } catch { /* nothing linked */ }
  await fs.rm(link, { recursive: true, force: true })
  await regenRegistry()
}

/**
 * Make every fragment of a project live under <projectDir>/kadr-fragments:
 * loose workspace folders MOVE there (symlink left behind), fragments that
 * exist only in the project folder (opened on another machine, or after the
 * workspace was cleaned) get their workspace symlink recreated. Valid
 * existing links are left alone. Returns the ids that changed.
 */
async function relocateFragments(projectDir: string, ids: string[]): Promise<string[]> {
  await ensureWorkspace()
  const changed: string[] = []
  // the project's kadr-lib link (a project opened on this machine for the
  // first time, or saved for the first time) — the registry must then load
  // its fonts, so it is regenerated when the link is new
  const hadLib = existsSync(join(PROJECTS_DIR(), projectKey(projectDir), 'fonts.ts'))
  if (ids.length) await ensureProjectLib(projectDir)
  const libNew = ids.length > 0 && !hadLib
  for (const id of ids) {
    assertId(id)
    const link = join(FRAG_DIR(), id)
    const target = join(projectFragHome(projectDir), id)
    const lst = await fs.lstat(link).catch(() => null)
    if (lst?.isSymbolicLink()) {
      const ok = existsSync(join(link, 'index.tsx'))
      if (!ok) {
        await fs.rm(link, { force: true })
        if (existsSync(join(target, 'index.tsx'))) {
          await fs.symlink(target, link, linkType)
          changed.push(id)
        }
      }
      continue
    }
    if (lst?.isDirectory()) {
      if (existsSync(target)) continue // conflict — keep both untouched
      await fs.mkdir(projectFragHome(projectDir), { recursive: true })
      try {
        await fs.rename(link, target)
      } catch {
        await fs.cp(link, target, { recursive: true }) // cross-device move
        await fs.rm(link, { recursive: true, force: true })
      }
      await fs.symlink(target, link, linkType)
      changed.push(id)
      continue
    }
    // nothing in the workspace at all — restore the link if the project has it
    if (existsSync(join(target, 'index.tsx'))) {
      await fs.symlink(target, link, linkType)
      changed.push(id)
    }
  }
  if (changed.length || libNew) await regenRegistry()
  return changed
}

/**
 * Write one generated file into a fragment's folder (through the workspace
 * link, so a project-owned fragment gets it in its real home). The name must be
 * a plain file name: the page may never pick a path, only a file inside a
 * folder this module already owns. Only the generated kinds are accepted.
 */
async function writeFragmentFile(id: string, name: string, content: string): Promise<string> {
  assertId(id)
  if (typeof name !== 'string' || !/^[A-Za-z0-9_-][A-Za-z0-9_.-]*\.(json|ts|tsx)$/.test(name) || name.includes('..')) {
    throw new Error('bad fragment file name')
  }
  if (typeof content !== 'string') throw new Error('fragment file content must be a string')
  const dir = await fs.realpath(join(FRAG_DIR(), id))
  const path = join(dir, name)
  // write-then-rename: vite's watcher must never see a half-written module
  const tmp = `${path}.part-${process.pid}`
  await fs.writeFile(tmp, content)
  await fs.rename(tmp, path)
  return path
}

/**
 * The fragment's params.json (defineParams in the runtime) MERGED with what
 * the Inspector changed: only the moved values are sent, and whatever the file
 * holds besides them — an edit by hand, by Claude — is kept. null resets the
 * file to {} (the declared defaults). Returns what the file now holds.
 */
async function writeFragmentParams(id: string, patch: Record<string, unknown> | null): Promise<Record<string, unknown>> {
  assertId(id)
  let next: Record<string, unknown> = {}
  if (patch !== null) {
    if (typeof patch !== 'object' || Array.isArray(patch)) throw new Error('params patch must be an object')
    try {
      const cur = JSON.parse(await fs.readFile(join(FRAG_DIR(), id, 'params.json'), 'utf8'))
      if (cur && typeof cur === 'object' && !Array.isArray(cur)) next = cur
    } catch { /* none yet, or unreadable: start over */ }
    for (const [k, v] of Object.entries(patch)) {
      if (typeof v === 'number' ? Number.isFinite(v) : typeof v === 'boolean' || typeof v === 'string') next[k] = v
    }
  }
  await writeFragmentFile(id, 'params.json', JSON.stringify(next, null, 2) + '\n')
  return next
}

/**
 * Content hash of what a fragment render depends on (names + mtimes + sizes):
 * its own folder, and — only when its sources import them — the project's
 * kadr-lib ('@lib/') and Kadr's runtime ('@kadr/'). Without that, an edit of
 * the shared code would have exported the old render. A fragment that uses
 * neither hashes exactly as before, so existing render caches stay valid.
 */
function fragmentHash(id: string): string {
  const h = createHash('sha1')
  const walk = (dir: string, skip?: (name: string) => boolean) => {
    let names: string[] = []
    try { names = readdirSync(dir).sort() } catch { return }
    for (const name of names) {
      if (name === 'node_modules' || skip?.(name)) continue
      const p = join(dir, name)
      const st = statSync(p)
      h.update(`${name}:${st.size}:${Math.round(st.mtimeMs)};`)
      if (st.isDirectory()) walk(p)
    }
  }
  const dir = join(FRAG_DIR(), id)
  walk(dir)
  let src = ''
  const read = (d: string) => {
    let names: string[] = []
    try { names = readdirSync(d) } catch { return }
    for (const n of names) {
      const p = join(d, n)
      if (/\.(tsx?|jsx?)$/.test(n)) { try { src += readFileSync(p, 'utf8') } catch { /* unreadable */ } }
    }
  }
  read(dir)
  if (src.includes('@lib/')) {
    let real = ''
    try { real = realpathSync(dir) } catch { /* not linked */ }
    if (basename(dirname(real)) === 'kadr-fragments') {
      h.update('@lib;')
      walk(join(dirname(dirname(real)), 'kadr-lib'))
    }
  }
  if (src.includes('@kadr/') || src.includes('@lib/')) {
    // three-preview is the preview's only; it never reaches a render
    h.update('@kadr;')
    walk(KADR_DIR(), (n) => n === 'three-preview.tsx')
  }
  return h.digest('hex').slice(0, 16)
}

/** A font file in kadr-lib/fonts: registered by the preview and the render. */
const FONT_FILE = /\.(woff2?|ttf|otf)$/i

/**
 * The render's entry: ONE composition. The old entry (src/index.ts → Root)
 * bundled every fragment in the workspace — 200+ on a real machine — so each
 * render first compiled all of them, and one fragment with a syntax error
 * broke every export on the machine. Always the same path: webpack names its
 * cache after the whole config, entry included, and a path per fragment would
 * start a new multi-gigabyte cache for each.
 */
async function writeRenderEntry(id: string): Promise<string> {
  const pd = await projectDirOf(id)
  const key = pd ? projectKey(pd) : null
  let fonts: string[] = []
  if (key) {
    try { fonts = (await fs.readdir(join(PROJECTS_DIR(), key, 'lib', 'fonts'))).filter((f) => FONT_FILE.test(f)).sort() } catch { /* none */ }
  }
  // the values dialled in with the Inspector's sliders (defineParams) — the
  // render reads the same params.json the preview does. Checked as JSON here:
  // a broken file would otherwise fail the whole bundle with a webpack error.
  let params = false
  try {
    const v = JSON.parse(await fs.readFile(join(FRAG_DIR(), id, 'params.json'), 'utf8'))
    params = !!v && typeof v === 'object' && !Array.isArray(v)
  } catch { /* none, or not usable: the declared defaults */ }
  const entry = join(WORKSPACE, 'src', '_entries', 'current.tsx')
  await fs.mkdir(dirname(entry), { recursive: true })
  await writeManaged(entry, [
    '// AUTO-GENERATED by Kadr for the render in progress — do not edit.',
    "import React from 'react'",
    "import { Composition, registerRoot } from 'remotion'",
    ...(fonts.length ? ["import { loadFont, fontFromFileName } from '../_kadr/runtime'"] : []),
    ...fonts.map((f, i) => `import font${i} from '../_projects/${key}/lib/fonts/${f}'`),
    ...fonts.map((f, i) => `loadFont(font${i}, ...fontFromFileName(${JSON.stringify(f)}))`),
    ...(params ? [
      "import { setParamValues } from '../_kadr/runtime'",
      `import params from '../fragments/${id}/params.json'`,
      'setParamValues(\'saved\', params)'
    ] : []),
    `import { fragment } from '../fragments/${id}'`,
    '',
    'const Root: React.FC = () => (',
    '  <Composition',
    `    id=${JSON.stringify(id)}`,
    '    component={fragment.component as React.FC}',
    '    durationInFrames={fragment.meta.durationInFrames}',
    '    fps={fragment.meta.fps}',
    '    width={fragment.meta.width}',
    '    height={fragment.meta.height}',
    '  />',
    ')',
    'registerRoot(Root)',
    ''
  ].join('\n'))
  return entry
}

/**
 * kadr.remotion.config.ts — what 'remotion render' runs with. The user's own
 * remotion.config.ts (GPU, concurrency…) is imported first when there is one
 * — a static import of a missing file would break the config bundle — and
 * Kadr's webpack part (src/_kadr/webpack.ts) is chained after it:
 * overrideWebpackConfig composes with the previous override.
 */
async function writeRenderConfig(): Promise<string> {
  const path = join(WORKSPACE, 'kadr.remotion.config.ts')
  const user = existsSync(join(WORKSPACE, 'remotion.config.ts'))
  await writeManaged(path, [
    '// Managed by Kadr — do not edit. Your own settings go in remotion.config.ts,',
    '// which is loaded first; this file adds what Kadr needs on top.',
    "import { Config, ConfigInternals } from '@remotion/cli/config'",
    ...(user ? ["import './remotion.config'"] : []),
    "import { kadrWebpack } from './src/_kadr/webpack'",
    '',
    'Config.overrideWebpackConfig(kadrWebpack(process.cwd()))',
    '',
    '// VP9 (every transparent fragment) with row multithreading: remotion runs',
    '// libvpx-vp9 with no speed flags. -row-mt 1 encodes 10-80 % faster depending',
    '// on the content; the frames are not bit-identical but equally close to the',
    '// source (measured against lossless frames: colour 55.72 vs 55.73 dB, alpha',
    '// 62.33 vs 62.34). Chained after an override of your own, if any;',
    '// KADR_VP9_ROW_MT=0 in the environment turns it off.',
    'const previousFfmpeg = ConfigInternals.getFfmpegOverrideFunction()',
    'Config.overrideFfmpegCommand(({ type, args }) => {',
    '  const out = previousFfmpeg({ type, args })',
    "  if (process.env.KADR_VP9_ROW_MT === '0' || out.includes('-row-mt')) return out",
    "  const i = out.indexOf('libvpx-vp9')",
    "  return i > 0 && out[i - 1].startsWith('-c:v') ? [...out.slice(0, i + 1), '-row-mt', '1', ...out.slice(i + 1)] : out",
    '})',
    ''
  ].join('\n'))
  return path
}

const renderDir = () => join(app.getPath('userData'), 'fragment-renders')
let renderChain: Promise<unknown> = Promise.resolve()
let activeRender: ChildProcess | null = null
let renderCancelled = false

/** remotion's frame scratch dirs (PNG per frame — gigabytes on a long render) */
const RENDER_SCRATCH = /^react-motion-render/
const scratchDirs = () => {
  try { return new Set(readdirSync(tmpdir()).filter((n) => RENDER_SCRATCH.test(n))) } catch { return new Set<string>() }
}
let scratchBefore = new Set<string>()

/** every process below `root`, whatever group or session it put itself in */
function processTree(root: number): number[] {
  let table: string
  try { table = execFileSync('ps', ['-eo', 'pid=,ppid='], { encoding: 'utf8' }) } catch { return [root] }
  const kids = new Map<number, number[]>()
  for (const line of table.split('\n')) {
    const [pid, ppid] = line.trim().split(/\s+/).map(Number)
    if (!pid) continue
    kids.set(ppid, [...(kids.get(ppid) ?? []), pid])
  }
  const out: number[] = []
  const walk = (p: number) => { out.push(p); for (const k of kids.get(p) ?? []) walk(k) }
  walk(root)
  return out
}

/**
 * Stop the running fragment render and everything under it. The whole TREE is
 * killed at once with SIGKILL, not the group with a polite TERM first — both
 * measured: remotion starts its headless Chrome in a process group of its own,
 * so a group kill never reached it, and on SIGTERM remotion launched a FRESH
 * Chrome on its way out, which was reparented to init and stayed. A snapshot of
 * the descendants killed in one pass leaves nothing able to spawn anything.
 * Its frame scratch dir is removed too (the one that appeared during this
 * render — a remotion render run by hand from a terminal is left alone).
 * Renders still queued behind it refuse to start until the next export clears
 * the flag.
 */
export function cancelFragmentRenders() {
  renderCancelled = true
  const child = activeRender
  if (!child?.pid) return
  if (process.platform === 'win32') {
    try { execFileSync('taskkill', ['/pid', String(child.pid), '/T', '/F']) } catch { /* already gone */ }
    return
  }
  for (const pid of processTree(child.pid)) {
    try { process.kill(pid, 'SIGKILL') } catch { /* already gone */ }
  }
  for (const name of scratchDirs()) {
    if (!scratchBefore.has(name)) void fs.rm(join(tmpdir(), name), { recursive: true, force: true })
  }
}

async function renderFragment(
  id: string,
  opts: { transparent?: boolean; range?: [number, number] } | undefined,
  onProgress: (p: number) => void
): Promise<{ path: string; cached: boolean; start: number; duration?: number }> {
  await ensureWorkspace()
  let transparent = !!opts?.transparent
  let fps = 0
  let total = 0
  try {
    const meta = JSON.parse(await fs.readFile(join(FRAG_DIR(), id, 'meta.json'), 'utf8'))
    if (opts?.transparent === undefined) transparent = !!meta.transparent
    fps = Number(meta.fps) || 0
    total = Math.floor(Number(meta.durationInFrames) || 0)
  } catch { /* meta is optional for the decision */ }
  const ext = transparent ? 'webm' : 'mp4'
  // 'q2' marks the render settings generation — old low-quality cache misses
  const base = `${id}-${fragmentHash(id)}-q2${transparent ? '-a' : ''}`
  const full = join(renderDir(), `${base}.${ext}`)
  // the picture's own length: the container runs longer (remotion's silent
  // audio track ends up to ~60 ms after the last frame), and a clip looping
  // past its end held the last frame for that long before wrapping
  const lengthOf = (frames: number) => (fps > 0 && frames > 0 ? frames / fps : undefined)
  try {
    await fs.access(full)
    return { path: full, cached: true, start: 0, duration: lengthOf(total) } // exact content already rendered
  } catch { /* not yet */ }
  // ONLY THE FRAMES THE EDIT USES (2026-10-08, an overnight export at 50 % after
  // 8 h). A project cut as windows of one continuous film (every scene a
  // fragment whose clip starts at inPoint = its place in the film) rendered each
  // fragment from frame 0 to its end: 33 scenes of a 26-minute film were
  // 1.6 million frames for the 93 thousand the edit shows, each scene slower
  // than the one before, about 35 hours in all. `range` is the stretch of the
  // composition (seconds) the clips need; frames are absolute, so the fragment
  // draws exactly what it drew in a full render, and the file simply starts at
  // `start` (the caller moves the clips' inPoint back by it). A full render
  // already on disk is always taken first — it contains every range.
  let f0 = 0
  let f1 = total - 1
  if (opts?.range && fps > 0 && total > 0) {
    f0 = Math.max(0, Math.min(total - 1, Math.floor(opts.range[0] * fps)))
    f1 = Math.max(f0, Math.min(total - 1, Math.ceil(opts.range[1] * fps)))
  }
  const partial = total > 0 && (f0 > 0 || f1 < total - 1)
  const out = partial ? join(renderDir(), `${base}-r${f0}-${f1}.${ext}`) : full
  const start = partial ? f0 / fps : 0
  const duration = lengthOf(partial ? f1 - f0 + 1 : total)
  if (partial) {
    try {
      await fs.access(out)
      return { path: out, cached: true, start, duration }
    } catch { /* not yet */ }
  }
  await fs.mkdir(renderDir(), { recursive: true })
  // Render into a sidecar and rename on success, so the presence of the cache
  // file always means "finished". Renderers get killed — the app quits, the
  // startup sweep reaps a leftover from a crashed session — and remotion
  // writes its output progressively, so a direct write leaves a TRUNCATED
  // file sitting exactly where the next export looks for a hit. An opaque
  // fragment would at least fail loudly (an mp4 without its moov box does not
  // probe), but a transparent one is a WebM: it parses fine and just ends
  // early, so the clip would silently freeze on its last rendered frame.
  const tmp = out.slice(0, -(ext.length + 1)) + `.part.${ext}`

  // Quality matters more than render time here (one cached render per
  // content hash): PNG frames avoid Remotion's default JPEG-80 pass, VP9
  // replaces VP8 for alpha (dramatically better on sharp graphics), and a
  // low CRF keeps this intermediate visually lossless — the final export
  // pass re-encodes it once more.
  const args = ['remotion', 'render', '--config=kadr.remotion.config.ts', 'src/_entries/current.tsx', id, tmp, '--log=error', '--image-format=png']
  if (transparent) args.push('--codec=vp9', '--pixel-format=yuva420p', '--crf=12')
  else args.push('--codec=h264', '--crf=15')
  if (partial) args.push(`--frames=${f0}-${f1}`)

  const extraEnv = await netEnv()
  const job = renderChain.then(async () => {
    try {
      await fs.access(out)
      return true // another caller rendered it while we waited in the queue
    } catch { /* still missing */ }
    try {
      if (renderCancelled) throw new Error('cancelled')
      // inside the queue: the entry is one file shared by every render
      await writeRenderEntry(id)
      await writeRenderConfig()
      await new Promise<void>((resolve, reject) => {
        // remotion runs chrome AND its own ffmpeg under this; a cancel kills
        // the whole tree (cancelFragmentRenders) — killing only npx once left
        // that ffmpeg encoding for minutes as an orphan nobody could reach
        const child = spawn('npx', args, {
          cwd: WORKSPACE,
          env: { ...process.env, ...extraEnv },
          stdio: ['ignore', 'pipe', 'pipe'],
          detached: process.platform !== 'win32'
        })
        activeRender = child
        scratchBefore = scratchDirs()
        // only the tail is parsed: the whole output re-scanned on every chunk
        // grew quadratically over a few thousand progress lines
        let tail = ''
        let rendered = 0
        let encoded = 0
        const onData = (c: Buffer) => {
          tail = (tail + c).slice(-4000)
          // remotion prints "Rendered 120/300" while drawing frames and
          // "Stitched 80/300" ("Encoded" in some versions) while encoding them
          // into the video — that second phase went unreported, and on a heavy
          // transparent fragment the export sat on one number for many minutes
          const r = [...tail.matchAll(/Rendered (\d+)\/(\d+)/g)].pop()
          const e = [...tail.matchAll(/(?:Stitched|Encoded) (\d+)\/(\d+)/g)].pop()
          if (r) rendered = Math.max(rendered, Number(r[1]) / Math.max(1, Number(r[2])))
          if (e) encoded = Math.max(encoded, Number(e[1]) / Math.max(1, Number(e[2])))
          onProgress(Math.min(0.99, 0.75 * rendered + 0.25 * encoded))
        }
        child.stdout!.on('data', onData)
        child.stderr!.on('data', onData)
        child.on('error', reject)
        child.on('close', (code) => {
          if (activeRender === child) activeRender = null
          if (renderCancelled) reject(new Error('cancelled'))
          else if (code === 0) resolve()
          else reject(new Error(`remotion render exited ${code}: ${tail.slice(-800)}`))
        })
      })
      await fs.rename(tmp, out)
    } catch (err) {
      await fs.unlink(tmp).catch(() => { /* nothing to clean */ })
      throw err
    }
    return false
  })
  renderChain = job.catch(() => { /* keep the queue alive */ })
  const cached = await job
  onProgress(1)
  return { path: out, cached, start, duration }
}

// ------------------------------------------------------------------ inspect

/** what fragments declared (player page ?inspect=1), by id + content hash */
const inspectCache = new Map<string, unknown>()

/**
 * What a fragment declares about itself — events, captions, its camera, whether
 * it is a window of a continuous film (fragment.inspect, @kadr/runtime) — read
 * in a hidden page that loads the module and never renders it. Cached by the
 * fragment's content hash, so an edit is re-read and nothing else is.
 */
async function inspectFragment(id: string): Promise<unknown> {
  assertId(id)
  await ensureWorkspace()
  if (!existsSync(join(FRAG_DIR(), id, 'index.tsx'))) throw new Error(`no fragment ${id}`)
  const key = `${id}:${fragmentHash(id)}`
  if (inspectCache.has(key)) return inspectCache.get(key)
  const { url } = await ensureServer()
  const win = new BrowserWindow({ show: false, webPreferences: { backgroundThrottling: false } })
  try {
    await win.loadURL(`${url}/?comp=${encodeURIComponent(id)}&inspect=1`)
    const deadline = Date.now() + 30000
    for (;;) {
      const r = await win.webContents.executeJavaScript('window.__kadrInspect ?? null', true).catch(() => null)
      if (r) {
        if (inspectCache.size > 100) inspectCache.clear()
        if ((r as { ok?: boolean }).ok) inspectCache.set(key, r)
        return r
      }
      if (Date.now() > deadline) throw new Error(`inspect ${id}: the page did not answer in 30 s`)
      await new Promise((res) => setTimeout(res, 200))
    }
  } finally {
    if (!win.isDestroyed()) win.destroy()
  }
}

/**
 * Play a fragment frame by frame in a hidden page (player ?collide=1) and
 * report which parts of Kadr's 3D kit intersect, on which frames. Offscreen
 * rendering keeps its frame loop running while nobody looks.
 */
async function collideFragment(id: string, stepSec = 1 / 15): Promise<unknown> {
  assertId(id)
  await ensureWorkspace()
  if (!existsSync(join(FRAG_DIR(), id, 'index.tsx'))) throw new Error(`no fragment ${id}`)
  let frames = 600
  try {
    const meta = JSON.parse(await fs.readFile(join(FRAG_DIR(), id, 'meta.json'), 'utf8'))
    frames = Math.max(1, Math.round(meta.durationInFrames / Math.max(1, Math.round(stepSec * meta.fps))))
  } catch { /* the page knows */ }
  const { url } = await ensureServer()
  const win = new BrowserWindow({
    show: false, width: 960, height: 540, enableLargerThanScreen: true,
    webPreferences: { offscreen: true, backgroundThrottling: false }
  })
  win.webContents.setFrameRate(60)
  try {
    await win.loadURL(`${url}/?comp=${encodeURIComponent(id)}&collide=1&step=${stepSec}`)
    const deadline = Date.now() + 60000 + frames * 1500
    for (;;) {
      const r = await win.webContents.executeJavaScript('window.__kadrCollide ?? null', true).catch(() => null)
      if (r) return r
      if (Date.now() > deadline) throw new Error(`collide ${id}: no answer`)
      await new Promise((res) => setTimeout(res, 300))
    }
  } finally {
    if (!win.isDestroyed()) win.destroy()
  }
}

// ---------------------------------------------------------------- typecheck

export interface FragmentTypeError { file: string; line: number; col: number; code: string; message: string }

/**
 * tsc over ONE fragment with the paths the preview and the render use
 * ('@lib/…' of its project, '@kadr/…'), reporting only errors in the
 * fragment, its project's kadr-lib and Kadr's runtime — not the thousands a
 * whole-workspace check prints for everything else there.
 */
async function typecheckFragment(id: string): Promise<{ ok: boolean; errors: FragmentTypeError[]; more: number }> {
  assertId(id)
  await ensureWorkspace()
  if (!existsSync(join(FRAG_DIR(), id, 'index.tsx'))) throw new Error(`no fragment ${id}`)
  const pd = await projectDirOf(id)
  const key = pd ? projectKey(pd) : null
  const cfgName = `tsconfig.kadr-check-${process.pid}.json`
  const cfg = {
    extends: './tsconfig.json',
    compilerOptions: {
      noEmit: true,
      preserveSymlinks: true,
      baseUrl: '.',
      paths: {
        '@kadr/*': ['src/_kadr/*'],
        ...(key ? { '@lib/*': [`src/_projects/${key}/lib/*`] } : {})
      }
    },
    include: [`src/fragments/${id}/**/*`, 'src/_kadr/assets.d.ts']
  }
  await fs.writeFile(join(WORKSPACE, cfgName), JSON.stringify(cfg, null, 2))
  try {
    const out = await new Promise<string>((resolve) => {
      const child = spawn(join(WORKSPACE, 'node_modules', '.bin', 'tsc'), ['-p', cfgName, '--pretty', 'false'], {
        cwd: WORKSPACE, stdio: ['ignore', 'pipe', 'pipe']
      })
      let text = ''
      child.stdout!.on('data', (c) => { text += c })
      child.stderr!.on('data', (c) => { text += c })
      child.on('error', (e) => resolve(String(e)))
      child.on('close', () => resolve(text))
    })
    const mine = [`src/fragments/${id}/`, 'src/_kadr/', ...(key ? [`src/_projects/${key}/`] : [])]
    const errors: FragmentTypeError[] = []
    for (const line of out.split('\n')) {
      const m = line.match(/^(.+?)\((\d+),(\d+)\): error (TS\d+): (.*)$/)
      if (!m || !mine.some((p) => m[1].startsWith(p))) continue
      errors.push({ file: m[1], line: Number(m[2]), col: Number(m[3]), code: m[4], message: m[5] })
    }
    const LIMIT = 60
    return { ok: errors.length === 0, errors: errors.slice(0, LIMIT), more: Math.max(0, errors.length - LIMIT) }
  } finally {
    await fs.unlink(join(WORKSPACE, cfgName)).catch(() => { /* gone */ })
  }
}

// ------------------------------------------------------------ pixel capture
// When a fragment clip carries GL-only features (masks, 3D, transitions,
// effects), the preview swaps its iframe for true pixels: a hidden offscreen
// window runs the same Player page and streams BGRA frames to the renderer,
// where the fragment becomes a regular compositor layer.

const captures = new Map<string, BrowserWindow>()

async function captureStart(
  getWin: () => BrowserWindow | null,
  id: string,
  url: string,
  w: number,
  h: number,
  fps: number
): Promise<void> {
  if (captures.has(id)) return
  const cw = Math.max(64, Math.round(w))
  const ch = Math.max(36, Math.round(h))
  const win = new BrowserWindow({
    show: false,
    frame: false,
    transparent: true,
    width: cw,
    height: ch,
    // newer Electron clamps even hidden windows to the display they land on —
    // with a portrait-rotated monitor first in the layout, a 1280×720 request
    // came back 1080×720 and captured frames arrived letterboxed + stretched
    enableLargerThanScreen: true,
    // never throttle: a parked hidden window stops repainting on seeks, so
    // paused-editor snapshots captured the PREVIOUS frame (stale-frame bug)
    webPreferences: { offscreen: true, backgroundThrottling: false }
  })
  captures.set(id, win)
  win.setContentSize(cw, ch) // re-assert: creation may still have clamped
  win.webContents.setFrameRate(Math.max(10, Math.min(60, Math.round(fps))))
  // A capture window is invisible, so is whatever goes wrong in it: a WebGL
  // context that could not be created or was lost, a page that crashed. Say
  // so in the editor's session log instead of handing back an empty frame.
  win.webContents.on('console-message', (e: any, ...legacy: any[]) => {
    const level = e?.level ?? legacy[0]
    const msg = String(e?.message ?? legacy[1] ?? '')
    const isError = level === 'error' || level === 3
    if (isError || /webgl|context lost|CONTEXT_LOST/i.test(msg)) {
      getWin()?.webContents.send('fragment:capture-log', { id, level: isError ? 'error' : 'warn', msg: msg.slice(0, 600) })
    }
  })
  win.webContents.on('render-process-gone', (_e, d) => {
    getWin()?.webContents.send('fragment:capture-log', { id, level: 'error', msg: `страница захвата упала: ${d.reason}` })
  })
  win.webContents.on('paint', (_ev, _dirty, image) => {
    const size = image.getSize()
    // BGRA, premultiplied — the compositor shader undoes both
    getWin()?.webContents.send('fragment:frame', {
      id, w: size.width, h: size.height, data: image.getBitmap()
    })
  })
  await win.loadURL(url)
}

/** Snapshots ask for the project's full width; live preview stays ≤1280
    (a full-width BGRA stream is ~500 MB/s over IPC). */
function captureResize(id: string, w: number, h: number) {
  const win = captures.get(id)
  if (!win || win.isDestroyed()) return
  const cw = Math.max(64, Math.round(w))
  const ch = Math.max(36, Math.round(h))
  const [ow, oh] = win.getContentSize()
  if (ow === cw && oh === ch) return
  win.setContentSize(cw, ch)
  win.webContents.invalidate()
}

function captureStop(id: string) {
  const win = captures.get(id)
  captures.delete(id)
  if (win && !win.isDestroyed()) win.destroy()
}

function captureSync(id: string, msg: unknown) {
  const win = captures.get(id)
  if (!win || win.isDestroyed()) return
  win.webContents
    .executeJavaScript(`window.postMessage(${JSON.stringify(msg)}, '*'); 0`, true)
    .catch(() => { /* page mid-load */ })
}

/** The frame the fragment page has really DRAWN (player page v3:
    window.__kadrDrawn) — −1 not ready yet, −2 no window. */
async function captureQuery(id: string): Promise<number> {
  const win = captures.get(id)
  if (!win || win.isDestroyed()) return -2
  try {
    const v = await win.webContents.executeJavaScript('window.__kadrDrawn ?? -1', true)
    return typeof v === 'number' ? v : -1
  } catch {
    return -1
  }
}

export function stopAllCaptures() {
  for (const id of [...captures.keys()]) captureStop(id)
}

// ---------------------------------------------------------------------- IPC

export function registerFragmentIpc(getWin: () => BrowserWindow | null) {
  const send = (id: string, phase: string, progress: number) =>
    getWin()?.webContents.send('fragment:progress', { id, phase, progress })

  ipcMain.handle('fragment:ensure', () =>
    ensureWorkspace((phase, p) => send('workspace', phase, p))
  )
  ipcMain.handle('fragment:server', () => ensureServer())
  ipcMain.handle('fragment:create', (_e, spec: FragmentSpec, projectDir?: string | null) =>
    createFragment(spec, projectDir))
  ipcMain.handle('fragment:delete', (_e, id: string) => deleteFragment(id))
  ipcMain.handle('fragment:relocate', (_e, projectDir: string, ids: string[]) =>
    relocateFragments(projectDir, ids))
  ipcMain.handle('fragment:write-file', (_e, id: string, name: string, content: string) =>
    writeFragmentFile(id, name, content))
  ipcMain.handle('fragment:params-write', (_e, id: string, patch: Record<string, unknown> | null) =>
    writeFragmentParams(id, patch))
  ipcMain.handle('fragment:render', (_e, id: string, opts?: { transparent?: boolean; range?: [number, number] }) => {
    renderCancelled = false
    return renderFragment(id, opts, (p) => send(id, 'render', p))
  })
  ipcMain.handle('fragment:cancel-render', () => cancelFragmentRenders())
  ipcMain.handle('fragment:typecheck', (_e, id: string) => typecheckFragment(id))
  ipcMain.handle('fragment:inspect', (_e, id: string) => inspectFragment(id))
  ipcMain.handle('fragment:collide', (_e, id: string, step?: number) => collideFragment(id, Number(step) || undefined))
  ipcMain.handle('fragment:capture-start', (_e, id: string, url: string, w: number, h: number, fps: number) =>
    captureStart(getWin, id, url, w, h, fps)
  )
  ipcMain.handle('fragment:capture-stop', (_e, id: string) => captureStop(id))
  ipcMain.handle('fragment:capture-resize', (_e, id: string, w: number, h: number) => captureResize(id, w, h))
  ipcMain.handle('fragment:capture-query', (_e, id: string) => captureQuery(id))
  ipcMain.on('fragment:capture-sync', (_e, id: string, msg: unknown) => captureSync(id, msg))
  app.on('before-quit', () => {
    stopServer()
    stopAllCaptures()
  })
}
