// «Реакция на звук»: bake the sound under a Remotion fragment clip into its
// folder, so the composition can move with the music — one value per
// COMPOSITION frame for loudness and three bands, plus the beats in
// composition seconds. Two files are written next to the entry:
//   audio.json — the data (regenerated on every bake)
//   audio.ts   — `useAudio()` / `audioAt()` / `beats`, the way to read it
// The composition imports audio.ts; nothing else about it changes.
//
// Composition time ↔ timeline: the preview drives frame
//   f = round(((t − clip.start)·speed + inPoint)·fps)
// (FragmentOverlays), so composition second τ plays at timeline
//   t = clip.start + (τ − inPoint)/speed.
// The WHOLE composition is baked, not just the visible part, so trimming the
// clip later does not leave frames without data.
//
// What was baked is fingerprinted into `clip.audioBake.hash` — the placement
// and every audio segment under the clip. A move, a trim, a gain change or a
// different music clip changes the hash: the Inspector says «устарело», and an
// export re-bakes before rendering (materializeFragments).
import { useEditor, findClip } from '@/state/store'
import { sampleCurve } from '@shared/audioAnalysis'
import type { AudioAnalysisResult, AudioSegment, Clip, Project } from '@shared/types'
import { collectRangeAudio } from './subtitles'
import { logInfo, logWarn } from './log'

/** default beat pulse decay in audio.ts, seconds */
export const BEAT_DECAY = 0.15

/**
 * Seconds of music listened to on each side of the composition. The beat
 * tracker needs context: its tempo comes from 8-second autocorrelation windows,
 * so a 4-second fragment analysed alone gets a shakier grid than the same
 * music analysed whole. The curves are also normalised over this wider window,
 * so a fragment does not blow a quiet passage up to full scale.
 */
export const BAKE_CONTEXT = 8

export interface BakePlan {
  fps: number
  frames: number
  /** timeline second of composition frame 0 (may be negative) */
  t0: number
  /** timeline seconds per composition frame */
  step: number
  /** span analysed: the composition ± BAKE_CONTEXT, timeline seconds (clamped at 0) */
  range: { start: number; end: number }
  segments: AudioSegment[]
  /** anything audible under the composition itself (not just in the context) */
  audible: boolean
  source: string
  hash: string
}

/** FNV-1a over a string, hex — a fingerprint, not a security boundary. */
function fnv(s: string): string {
  let h = 0x811c9dc5
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i)
    h = Math.imul(h, 0x01000193) >>> 0
  }
  return h.toString(16).padStart(8, '0')
}

/** What a bake of this clip would listen to — pure, so staleness is a comparison. */
export function bakePlan(project: Project, clip: Clip, source = 'mix'): BakePlan | null {
  if (clip.kind !== 'remotion' || !clip.fragmentMeta) return null
  const fps = clip.fragmentMeta.fps || 60
  const frames = Math.max(1, Math.round(clip.fragmentMeta.durationInFrames || 1))
  const speed = clip.speed || 1
  const t0 = clip.start - (clip.inPoint || 0) / speed
  const step = 1 / (fps * speed)
  const end = t0 + frames * step
  const range = { start: Math.max(0, t0 - BAKE_CONTEXT), end: end + BAKE_CONTEXT }
  const filter = source === 'mix' ? undefined : { trackIds: [source] }
  const segments = range.end > range.start ? collectRangeAudio(project, range.start, range.end, filter) : []
  const audible = end > Math.max(0, t0) &&
    collectRangeAudio(project, Math.max(0, t0), end, filter).length > 0
  const hash = fnv(JSON.stringify({ fps, frames, t0: +t0.toFixed(6), speed, source, segments }))
  return { fps, frames, t0, step, range, segments, audible, source, hash }
}

export type BakeState = 'none' | 'fresh' | 'stale'

export function bakeState(project: Project, clip: Clip): BakeState {
  if (!clip.audioBake) return 'none'
  const plan = bakePlan(project, clip, clip.audioBake.source)
  return plan && plan.hash === clip.audioBake.hash ? 'fresh' : 'stale'
}

/** The generated reader. Kept free of project data so it never needs regenerating. */
export const AUDIO_TS = `// Generated by Kadr («Реакция на звук»). The sound under this clip, baked into
// audio.json — one value per COMPOSITION frame. Both files are overwritten on
// every bake: keep your own code in index.tsx and read the sound from here.
//
//   import { useAudio } from './audio'
//   const a = useAudio()          // inside a component
//   a.level, a.bass, a.mid, a.treble   0..1, normalised over the clip, smoothed
//   a.beat    1 on every beat, decaying to 0 in ~0.15 s
//   a.accent  the same, only on the accented (strongest) beats
//   a.beatIndex / a.sinceBeat / a.bpm
//
// Taste (from /brag): let the music make EXISTING things breathe — a glow, a
// scale of a few percent, a background warming up — not an equaliser, not a
// strobe, and never text that pulses so hard it cannot be read.
import { useCurrentFrame, useVideoConfig } from 'remotion'
import data from './audio.json'

export interface AudioFrame {
  level: number
  bass: number
  mid: number
  treble: number
  beat: number
  accent: number
  /** last beat at or before now, -1 before the first */
  beatIndex: number
  /** seconds since that beat, Infinity before the first */
  sinceBeat: number
  bpm: number
}

export interface BeatInfo {
  /** composition seconds */
  time: number
  /** 0..1 */
  strength: number
  strong: boolean
}

const D = data as unknown as {
  fps: number
  bpm: number
  level: number[]
  bass: number[]
  mid: number[]
  treble: number[]
  beats: [number, number, number][]
}

export const beats: BeatInfo[] = D.beats.map(([time, strength, strong]) => ({ time, strength, strong: strong === 1 }))
export const bpm = D.bpm

const pick = (arr: number[], f: number) => (arr.length ? arr[Math.max(0, Math.min(arr.length - 1, f))] : 0)

/** index of the last beat at or before t (seconds), -1 if none */
function lastBeat(t: number, strongOnly: boolean): number {
  let lo = 0
  let hi = beats.length - 1
  let ans = -1
  while (lo <= hi) {
    const mid = (lo + hi) >> 1
    if (beats[mid].time <= t + 1e-6) {
      ans = mid
      lo = mid + 1
    } else hi = mid - 1
  }
  if (strongOnly) while (ans >= 0 && !beats[ans].strong) ans--
  return ans
}

/** The sound at a composition frame. \`decay\` = seconds for a beat pulse to fall to ~5 %. */
export function audioAt(frame: number, fps: number, decay = ${BEAT_DECAY}): AudioFrame {
  // the data was baked at the composition's own fps; resample if asked for another
  const f = Math.round((frame / fps) * (D.fps || fps))
  const t = frame / fps
  const i = lastBeat(t, false)
  const j = lastBeat(t, true)
  const pulse = (k: number) => (k < 0 ? 0 : Math.exp((-3 * (t - beats[k].time)) / Math.max(1e-3, decay)))
  return {
    level: pick(D.level, f),
    bass: pick(D.bass, f),
    mid: pick(D.mid, f),
    treble: pick(D.treble, f),
    beat: pulse(i),
    accent: pulse(j),
    beatIndex: i,
    sinceBeat: i < 0 ? Infinity : t - beats[i].time,
    bpm: D.bpm
  }
}

/** The sound at the current frame of the composition. */
export function useAudio(decay?: number): AudioFrame {
  const frame = useCurrentFrame()
  const { fps } = useVideoConfig()
  return audioAt(frame, fps, decay)
}
`

/** Bake from an analysis already made for plan.range (pure: builds the audio.json object). */
export function audioJson(plan: BakePlan, a: AudioAnalysisResult, clip: Clip) {
  const times: number[] = []
  // times relative to the analysed range: composition frame k plays at t0 + k·step
  for (let k = 0; k < plan.frames; k++) times.push(plan.t0 + k * plan.step - plan.range.start)
  const speed = clip.speed || 1
  const inPoint = clip.inPoint || 0
  const beats = a.beats
    .map((b) => {
      const tl = plan.range.start + b.time
      const tau = inPoint + (tl - clip.start) * speed
      return [Math.round(tau * 1000) / 1000, Math.round(b.intensity * 1000) / 1000, b.strong ? 1 : 0]
    })
    .filter(([tau]) => tau >= 0 && tau <= plan.frames / plan.fps + 1e-6)
  return {
    generatedBy: 'Kadr — Реакция на звук',
    fps: plan.fps,
    frames: plan.frames,
    bpm: a.tempo,
    source: plan.source,
    timeline: { start: +plan.t0.toFixed(4), end: +(plan.t0 + plan.frames * plan.step).toFixed(4) },
    level: sampleCurve(a.curves.rms, a.frameRate, times),
    bass: sampleCurve(a.curves.bass, a.frameRate, times),
    mid: sampleCurve(a.curves.mid, a.frameRate, times),
    treble: sampleCurve(a.curves.treble, a.frameRate, times),
    beats
  }
}

export interface BakeResult {
  clipId: string
  fragmentId: string
  files: string[]
  frames: number
  bpm: number
  beats: number
  /** false = there is no sound under the clip; files were still written (flat zeros) */
  audible: boolean
}

/**
 * Bake the sound under `project`'s clip into its fragment and record the bake
 * on the live clip. `project` is normally the live one; the exporter passes the
 * snapshot it is rendering.
 */
export async function bakeClip(project: Project, clipId: string, source = 'mix'): Promise<BakeResult> {
  const found = findClip(project, clipId)
  if (!found) throw new Error('клип не найден')
  const clip = found.clip
  if (clip.kind !== 'remotion' || !clip.fragmentId) throw new Error('реакция на звук — только для фрагментов (Remotion)')
  if (source !== 'mix' && !project.tracks.some((t) => t.id === source)) throw new Error('дорожка-источник не найдена')
  const plan = bakePlan(project, clip, source)!
  const duration = Math.max(0.05, plan.range.end - plan.range.start)
  const analysis = await window.kadr.audioAnalyze({ audioSegments: plan.segments, duration })
  const json = audioJson(plan, analysis, clip)
  const files = [
    await window.kadr.fragmentWriteFile(clip.fragmentId, 'audio.json', JSON.stringify(json)),
    await window.kadr.fragmentWriteFile(clip.fragmentId, 'audio.ts', AUDIO_TS)
  ]
  // record on the LIVE clip (the exporter's snapshot is a copy); no undo entry —
  // the files on disk are not part of the undo stack either
  const live = findClip(useEditor.getState().project, clipId)
  if (live) {
    useEditor.setState((s) => {
      const p = { ...s.project }
      p.tracks = p.tracks.map((t) => (t.clips.some((c) => c.id === clipId)
        ? { ...t, clips: t.clips.map((c) => (c.id === clipId
            ? { ...c, audioBake: { hash: plan.hash, source, at: Date.now() } } : c)) }
        : t))
      return { project: p }
    })
  }
  logInfo('звук→фрагмент', `${clip.fragmentId}: ${json.frames} кадров, ${json.beats.length} битов, ${analysis.tempo.toFixed(1)} BPM`)
  return {
    clipId,
    fragmentId: clip.fragmentId,
    files,
    frames: json.frames,
    bpm: analysis.tempo,
    beats: json.beats.length,
    audible: plan.audible
  }
}

/** Bake the live clip (UI / scripts). */
export function bakeAudio(clipId: string, opts: { source?: string } = {}): Promise<BakeResult> {
  const p = useEditor.getState().project
  const clip = findClip(p, clipId)?.clip
  return bakeClip(p, clipId, opts.source ?? clip?.audioBake?.source ?? 'mix')
}

/**
 * Before an export: re-bake every fragment whose bake no longer matches what
 * is under it, so the render hears the edit as it is now. A fragment used by
 * several clips at different places cannot be right for all of them — that is
 * reported and left alone.
 */
export async function refreshStaleBakes(project: Project): Promise<number> {
  const clips = project.tracks.flatMap((t) => t.clips).filter((c) => c.kind === 'remotion' && c.fragmentId)
  let n = 0
  for (const clip of clips) {
    if (!clip.audioBake || bakeState(project, clip) !== 'stale') continue
    const users = clips.filter((c) => c.fragmentId === clip.fragmentId)
    if (users.length > 1) {
      logWarn('звук→фрагмент', `фрагмент ${clip.fragmentId} стоит на таймлайне ${users.length} раза — звук запечён для одного места, обновите вручную`)
      continue
    }
    await bakeClip(project, clip.id, clip.audioBake.source)
    n++
  }
  return n
}
