// Neon wave: an audio-reactive Remotion fragment that reproduces the user's
// Blender preset (a glowing sine line whose wiggle frequency and height follow
// loudness) without Blender. The loudness envelope is computed in main
// (audio:envelope — Blender's "Bake Sound" follower, verified exact) and baked
// into the generated TSX together with the style, like auto-captions. Geometry
// is the preset's node graph in closed form (verified against Blender's
// evaluated mesh to 0.03 px); colour/glow/streaks are a canvas imitation of
// EEVEE + Filmic + Glare, calibrated against the preset's rendered frames.
import { useEditor } from '@/state/store'
import type { FragmentSpec } from '@shared/types'
import { collectRangeAudio } from './subtitles'
import { createFragment } from './fragments'

export interface NeonWaveStyle {
  // ---- geometry (Blender units; the preset's camera gives 128.6 px/unit at 1920 wide)
  /** points along the line */
  samples: number
  /** px per unit at a 1920-wide frame (scales with width) */
  pxPerUnit: number
  /** tube radius, units */
  tubeRadius: number
  /** height factor: z = amp · e · (wave − 0.5) · window */
  amp: number
  /** wave frequency factor: sin(wiggle · x · e + phase · t − π/2) */
  wiggle: number
  /** wave phase speed, rad/s (frame/2 at the preset's 24 fps) */
  phase: number
  /** static window frequency: sin(window · x − π/2) */
  window: number
  /** window ColorRamp: [position, value] — piecewise linear */
  ramp: [number, number][]
  /** Blender compositor Lens Distortion «Distort» (−0.3). Applied exactly like Blender's
      ScreenLensDistortion: per-axis normalised uv·sc with sc = 1/(1+max k) (the whole picture
      shrinks towards the centre for negative k), source = uv·d, d = 1/(1+√(1−4k·r²)). */
  distortion: number
  // ---- colour
  /** emission ColorRamp stops [position, [r,g,b] linear 0..1] */
  colorStops: [number, [number, number, number]][]
  /** colour wave over normalised height: sin(colorWave · zn + colorPhase · t − π/2) */
  colorWave: number
  /** rad/s (frame/20 at 24 fps) */
  colorPhase: number
  /** core tone-mapping: sRGB(1 − exp(−coreExposure · c)) — emission 10× through Filmic (4.9 matches the preset's render) */
  coreExposure: number
  // ---- glow
  /** core stroke width multiplier over the tube diameter */
  coreWidthMul: number
  /** soft passes of the saturated colour: [blur px, alpha, stroke width px] at 1920 wide, SOURCE space (the glow itself comes from the streaks) */
  halo: [number, number, number][]
  /** Glare Streaks — the preset's only glow: the saturated line copied along `angles` (degrees) every `step` source px, alpha fade^j; calibrated to 0.3·exp(−d/28 px) in the output */
  streak: { strength: number; fade: number; copies: number; step: number; angles: number[] }
  /** Lens Distortion «Dispersion» (0.2): each channel gets its own k — R = distort + 0.25·d,
      B = distort − 0.25·d — so blue reaches furthest out (the blue tails at the line ends) */
  dispersion: number
  /** canvas resolution factor used only in the live preview (the render is 1) */
  previewScale: number
  background: string
}

export const NEON_WAVE_DEFAULTS: NeonWaveStyle = {
  samples: 2000,
  pxPerUnit: 128.6,
  tubeRadius: 0.02,
  amp: 10 / 3,
  wiggle: 20,
  phase: 12,
  window: 0.6,
  ramp: [[0, 2.0], [0.1682, 0.0392], [0.2682, 1.0], [0.55, 0.1559], [0.9409, 0]],
  distortion: -0.3,
  colorStops: [[0, [0.105, 0.359, 1.0]], [0.418, [0, 0.0007, 0.8875]], [1, [1.0, 0.033, 0.775]]],
  colorWave: 4,
  colorPhase: 1.2,
  coreExposure: 4.9,
  coreWidthMul: 1.7,
  halo: [[6.5, 0.1, 9]],
  streak: { strength: 0.34, fade: 0.76, copies: 24, step: 6.5, angles: [0, 90, 180, 270] },
  dispersion: 0.2,
  previewScale: 0.5,
  background: '#000'
}

/** The fragment source. `__ENV__` / `__STYLE__` are substituted by neonWaveTsx. */
const TSX = `import React, { useLayoutEffect, useRef } from 'react'
import { AbsoluteFill, useCurrentFrame, useVideoConfig, getRemotionEnvironment } from 'remotion'
import meta from './meta.json'

// Generated by Kadr («Неоновая волна»). Edit freely: S holds every style knob,
// ENV is the loudness per frame (Blender "Bake Sound" follower: 5 ms attack,
// 200 ms release). Time runs in SECONDS (t = frame / fps), so the motion speed
// does not depend on the composition fps.
const ENV: number[] = __ENV__
const S = __STYLE__

type Pt = { x: number; y: number; c: number }

function rampLin(stops: [number, number][], v: number): number {
  if (v <= stops[0][0]) return stops[0][1]
  const last = stops[stops.length - 1]
  if (v >= last[0]) return last[1]
  for (let i = 1; i < stops.length; i++) {
    const [p1, c1] = stops[i]
    if (v <= p1) {
      const [p0, c0] = stops[i - 1]
      return c0 + ((c1 - c0) * (v - p0)) / (p1 - p0)
    }
  }
  return last[1]
}

// colour LUT (linear 0..1): Blender's ColorRamp in B-Spline mode — a uniform cubic
// B-spline over the stops (BKE_colorband_evaluate: weights (1−t)³/6, (3t³−6t²+4)/6,
// (−3t³+3t²+3t+1)/6, t³/6 on left-left/left/right/right-right, ends duplicated).
// It APPROXIMATES the stops instead of passing through them — that is what makes the
// preset's colour transitions soft; a smoothstep between stops looked banded.
const LUT: [number, number, number][] = (() => {
  const st = S.colorStops as [number, [number, number, number]][]
  const n = st.length
  const out: [number, number, number][] = []
  for (let i = 0; i < 256; i++) {
    const v = i / 255
    let r = n - 1 // first stop with pos > v (right neighbour); n−1 when past the last
    for (let k = 0; k < n; k++) if (st[k][0] > v) { r = k; break }
    if (r === 0) { out.push(st[0][1]); continue }
    if (v >= st[n - 1][0]) { out.push(st[n - 1][1]); continue }
    const l = r - 1
    const pl = st[Math.max(0, l - 1)][1], p0 = st[l][1], p1 = st[r][1], pr = st[Math.min(n - 1, r + 1)][1]
    const t = (v - st[l][0]) / (st[r][0] - st[l][0])
    const t2 = t * t, t3 = t2 * t
    const w0 = (-t3 + 3 * t2 - 3 * t + 1) / 6, w1 = (3 * t3 - 6 * t2 + 4) / 6
    const w2 = (-3 * t3 + 3 * t2 + 3 * t + 1) / 6, w3 = t3 / 6
    out.push([0, 1, 2].map((c) => w0 * pl[c] + w1 * p0[c] + w2 * p1[c] + w3 * pr[c]) as [number, number, number])
  }
  return out
})()
const toS = (v: number) => Math.round(255 * Math.pow(Math.max(0, Math.min(1, v)), 1 / 2.2))
/** halo: the ramp colour as is (saturated); core: tone-mapped emission (exposure > 0) */
const rgb = (c: [number, number, number], exposure: number) => {
  const f = (v: number) => (exposure > 0 ? toS(1 - Math.exp(-exposure * v)) : toS(v))
  return 'rgb(' + f(c[0]) + ',' + f(c[1]) + ',' + f(c[2]) + ')'
}

/** the preset's geometry: line x ∈ [−6, 6], z = amp·e·(wave − 0.5)·ramp(window) */
function points(e: number, t: number, W: number, H: number): Pt[] {
  const n = S.samples
  const ppu = (W * S.pxPerUnit) / 1920
  const cx = W / 2
  const cy = H / 2
  const zs = new Float32Array(n)
  let zmin = Infinity
  let zmax = -Infinity
  for (let i = 0; i < n; i++) {
    const x = -6 + (12 * i) / (n - 1)
    const w = 0.5 + 0.5 * Math.sin(S.wiggle * x * e + S.phase * t - Math.PI / 2)
    const w2 = 0.5 + 0.5 * Math.sin(S.window * x - Math.PI / 2)
    const z = S.amp * e * (w - 0.5) * rampLin(S.ramp as [number, number][], w2)
    zs[i] = z
    if (z < zmin) zmin = z
    if (z > zmax) zmax = z
  }
  // emission colour rides Generated coords = height normalised to the bounding box
  const lo = zmin - S.tubeRadius
  const span = Math.max(1e-6, zmax - zmin + 2 * S.tubeRadius)
  const out: Pt[] = []
  for (let i = 0; i < n; i++) {
    const x = -6 + (12 * i) / (n - 1)
    const z = zs[i]
    const zn = span > 1e-5 ? (z - lo) / span : 0.5
    const c = 0.5 + 0.5 * Math.sin(S.colorWave * zn + S.colorPhase * t - Math.PI / 2)
    out.push({ x: cx + ppu * x, y: cy - ppu * z, c })
  }
  return out
}

/** stroke the polyline in short runs so the colour can follow the height */
function strokeRuns(ctx: CanvasRenderingContext2D, pts: Pt[], width: number, exposure: number, run = 3) {
  ctx.lineWidth = width
  ctx.lineCap = 'round'
  ctx.lineJoin = 'round'
  for (let i = 0; i < pts.length - 1; i += run) {
    const j = Math.min(pts.length - 1, i + run)
    const cm = pts[Math.min(pts.length - 1, i + (run >> 1))].c
    ctx.strokeStyle = rgb(LUT[Math.max(0, Math.min(255, Math.round(cm * 255)))], exposure)
    ctx.beginPath()
    ctx.moveTo(pts[i].x, pts[i].y)
    for (let k = i + 1; k <= j; k++) ctx.lineTo(pts[k].x, pts[k].y)
    ctx.stroke()
  }
}

/** pixel box around the line (+ margin) so the layer passes skip the empty frame */
function bbox(pts: Pt[], margin: number, W: number, H: number) {
  let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity
  for (const p of pts) {
    if (p.x < x0) x0 = p.x
    if (p.x > x1) x1 = p.x
    if (p.y < y0) y0 = p.y
    if (p.y > y1) y1 = p.y
  }
  const bx = Math.max(0, Math.floor(x0 - margin))
  const by = Math.max(0, Math.floor(y0 - margin))
  return { x: bx, y: by, w: Math.min(W, Math.ceil(x1 + margin)) - bx, h: Math.min(H, Math.ceil(y1 + margin)) - by }
}

type Layers = { q: number; scene: HTMLCanvasElement; core: HTMLCanvasElement; glow: HTMLCanvasElement; halo: HTMLCanvasElement; streak: HTMLCanvasElement }

/**
 * Blender's compositor Lens Distortion as a WebGL pass (COM_ScreenLensDistortionOperation):
 * for every OUTPUT pixel, uv = sc·(xy − c)/c per axis, r² = uv·uv, t = 1 − 4k·r²,
 * d = 1/(1+√t), source = uv·d + ½ — sampled once per channel with that channel's k
 * (dispersion). With k < 0 the centre shrinks by 1/sc ≈ 0.75 and the blue channel reaches
 * furthest out. Returns null when WebGL is unavailable (the scene is then shown as is).
 */
type Warp = { gl: WebGLRenderingContext; tex: WebGLTexture; uK: WebGLUniformLocation; uSc: WebGLUniformLocation }
function makeWarp(cv: HTMLCanvasElement): Warp | null {
  const gl = cv.getContext('webgl', { premultipliedAlpha: false, antialias: false, preserveDrawingBuffer: true })
  if (!gl) return null
  const vs = 'attribute vec2 p; varying vec2 v; void main(){ v = p * 0.5 + 0.5; gl_Position = vec4(p, 0.0, 1.0); }'
  const fs =
    'precision highp float; varying vec2 v; uniform sampler2D t; uniform vec3 k; uniform float sc;' +
    'float ch(float kk, int c){ vec2 uv = sc * (v * 2.0 - 1.0); float r2 = dot(uv, uv); float tt = 1.0 - 4.0 * kk * r2;' +
    ' if (tt < 0.0) return 0.0; float d = 1.0 / (1.0 + sqrt(tt)); vec2 s = uv * d + 0.5;' +
    ' if (s.x < 0.0 || s.x > 1.0 || s.y < 0.0 || s.y > 1.0) return 0.0; vec3 px = texture2D(t, s).rgb;' +
    ' return c == 0 ? px.r : (c == 1 ? px.g : px.b); }' +
    'void main(){ gl_FragColor = vec4(ch(k.r, 0), ch(k.g, 1), ch(k.b, 2), 1.0); }'
  const sh = (type: number, src: string) => {
    const o = gl.createShader(type)!
    gl.shaderSource(o, src)
    gl.compileShader(o)
    return o
  }
  const prog = gl.createProgram()!
  gl.attachShader(prog, sh(gl.VERTEX_SHADER, vs))
  gl.attachShader(prog, sh(gl.FRAGMENT_SHADER, fs))
  gl.linkProgram(prog)
  if (!gl.getProgramParameter(prog, gl.LINK_STATUS)) return null
  gl.useProgram(prog)
  const buf = gl.createBuffer()
  gl.bindBuffer(gl.ARRAY_BUFFER, buf)
  gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1, -1, 1, -1, -1, 1, 1, 1]), gl.STATIC_DRAW)
  const loc = gl.getAttribLocation(prog, 'p')
  gl.enableVertexAttribArray(loc)
  gl.vertexAttribPointer(loc, 2, gl.FLOAT, false, 0, 0)
  const tex = gl.createTexture()!
  gl.activeTexture(gl.TEXTURE0)
  gl.bindTexture(gl.TEXTURE_2D, tex)
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR)
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR)
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE)
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE)
  gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true)
  gl.uniform1i(gl.getUniformLocation(prog, 't'), 0)
  return { gl, tex, uK: gl.getUniformLocation(prog, 'k')!, uSc: gl.getUniformLocation(prog, 'sc')! }
}
function runWarp(w: Warp, scene: HTMLCanvasElement, distort: number, dispersion: number) {
  const { gl } = w
  const clampK = (v: number) => Math.max(-0.999, Math.min(1, v))
  const kg = clampK(distort)
  const dd = 0.25 * Math.max(0, Math.min(1, dispersion))
  const kr = clampK(kg + dd)
  const kb = clampK(kg - dd)
  const maxk = Math.max(kr, kg, kb)
  const sc = 1 / (1 + maxk) // Blender: fit off
  gl.viewport(0, 0, scene.width, scene.height)
  gl.bindTexture(gl.TEXTURE_2D, w.tex)
  gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, scene)
  gl.uniform3f(w.uK, kr, kg, kb)
  gl.uniform1f(w.uSc, sc)
  gl.drawArrays(gl.TRIANGLE_STRIP, 0, 4)
}

const Frag: React.FC = () => {
  const frame = useCurrentFrame()
  const { fps, width, height } = useVideoConfig()
  const ref = useRef<HTMLCanvasElement>(null)
  const layers = useRef<Layers | null>(null)
  const warp = useRef<Warp | null | undefined>(undefined) // undefined = not tried yet

  useLayoutEffect(() => {
    const cv = ref.current
    if (!cv) return
    const rendering = getRemotionEnvironment().isRendering
    const q = rendering ? 1 : S.previewScale
    const W = Math.round(width * q)
    const H = Math.round(height * q)
    if (cv.width !== W || cv.height !== H) {
      cv.width = W
      cv.height = H
    }
    let L = layers.current
    if (!L || L.q !== q || L.core.width !== W || L.core.height !== H) {
      const mk = () => {
        const c = document.createElement('canvas')
        c.width = W
        c.height = H
        return c
      }
      L = { q, scene: mk(), core: mk(), glow: mk(), halo: mk(), streak: mk() }
      layers.current = L
    }
    if (warp.current === undefined) warp.current = makeWarp(cv)
    // the scene is composed in SOURCE space (what Blender's render layer sees); the
    // Lens Distortion pass below maps it onto the visible canvas
    const ctx = (warp.current ? L.scene : cv).getContext('2d')!
    const e = ENV.length ? ENV[Math.min(frame, ENV.length - 1)] || 0 : 0
    const t = frame / fps
    const pts = points(e, t, W, H)
    const sc = W / 1920 // px sizes in S are given at 1920 wide
    const tube = 2 * S.tubeRadius * ((W * S.pxPerUnit) / 1920)

    const st = S.streak
    const streakLen = st.copies * st.step * sc
    const maxBlur = Math.max(...(S.halo as [number, number, number][]).map((h) => h[0] * sc))
    const B = bbox(pts, Math.ceil(Math.max(streakLen, 3 * maxBlur, 40 * sc) + 4), W, H)
    // drawImage restricted to the box: source rect → same place
    const blit = (c: CanvasRenderingContext2D, src: HTMLCanvasElement, dx = 0, dy = 0) =>
      c.drawImage(src, B.x, B.y, B.w, B.h, B.x + dx, B.y + dy, B.w, B.h)

    // core: the emissive tube (bright, pushed towards white)
    const core = L.core.getContext('2d')!
    core.clearRect(0, 0, W, H)
    strokeRuns(core, pts, tube * S.coreWidthMul, S.coreExposure)
    // glow source: the same line in its saturated ramp colour (what the streaks smear)
    const glow = L.glow.getContext('2d')!
    glow.clearRect(0, 0, W, H)
    strokeRuns(glow, pts, tube * S.coreWidthMul * 1.2, 0)

    // background + blurred halo passes (saturated colour, redrawn per pass at that width)
    const halo = L.halo.getContext('2d')!
    ctx.globalCompositeOperation = 'source-over'
    ctx.globalAlpha = 1
    ctx.filter = 'none'
    ctx.fillStyle = S.background
    ctx.fillRect(0, 0, W, H)
    ctx.globalCompositeOperation = 'lighter'
    for (const [blur, alpha, w] of S.halo as [number, number, number][]) {
      halo.clearRect(0, 0, W, H)
      strokeRuns(halo, pts, w * sc, 0)
      ctx.filter = 'blur(' + Math.max(0.5, blur * sc) + 'px)'
      ctx.globalAlpha = alpha
      blit(ctx, L.halo)
    }

    // Glare streaks: the core smeared along each angle with geometric fade
    if (st.strength > 0 && st.copies > 0) {
      const sk = L.streak.getContext('2d')!
      sk.globalCompositeOperation = 'source-over'
      sk.globalAlpha = 1
      sk.clearRect(0, 0, W, H)
      sk.globalCompositeOperation = 'lighter'
      // the preview draws every other copy at double step (same reach, half the work)
      const every = rendering ? 1 : 2
      const copies = Math.max(1, Math.round(st.copies / every))
      const stepPx = st.step * sc * every
      for (const a of st.angles) {
        const dx = Math.cos((a * Math.PI) / 180)
        const dy = -Math.sin((a * Math.PI) / 180)
        for (let j = 1; j <= copies; j++) {
          sk.globalAlpha = Math.pow(st.fade, j * every)
          blit(sk, L.glow, dx * j * stepPx, dy * j * stepPx)
        }
      }
      // the copies running along the line land on the line itself; that energy
      // is already inside the core's tone-mapping, so cut it out
      sk.globalCompositeOperation = 'destination-out'
      sk.globalAlpha = 1
      blit(sk, L.glow)
      ctx.filter = 'blur(' + Math.max(0.5, stepPx * 0.8) + 'px)'
      ctx.globalAlpha = st.strength
      blit(ctx, L.streak)
    }

    // the core on top
    ctx.filter = 'blur(' + Math.max(0.3, 0.6 * sc) + 'px)'
    ctx.globalAlpha = 1
    blit(ctx, L.core)
    ctx.filter = 'none'

    ctx.globalCompositeOperation = 'source-over'
    ctx.globalAlpha = 1
    if (warp.current) runWarp(warp.current, L.scene, S.distortion, S.dispersion)
  }, [frame, fps, width, height])

  return (
    <AbsoluteFill style={{ background: S.background }}>
      <canvas ref={ref} style={{ width: '100%', height: '100%', display: 'block' }} />
    </AbsoluteFill>
  )
}

export const fragment = { component: Frag, meta }
`

/** Generate the fragment source for an envelope (one value per frame) and a style. */
export function neonWaveTsx(env: number[], meta: FragmentSpec, style: NeonWaveStyle = NEON_WAVE_DEFAULTS): string {
  const frames = Math.max(1, meta.durationInFrames)
  const fixed = env.slice(0, frames).map((v) => +(+v || 0).toFixed(4))
  while (fixed.length < frames) fixed.push(fixed.length ? fixed[fixed.length - 1] : 0)
  return TSX.replace('__ENV__', JSON.stringify(fixed)).replace('__STYLE__', JSON.stringify(style, null, 2))
}

export interface NeonWaveOpts {
  range: { start: number; end: number }
  /** 'mix' = every audible track in the range; {trackId} = only that track's mix */
  source?: 'mix' | { trackId: string }
  style?: Partial<NeonWaveStyle>
  /** fragment name (composition id derives from it) */
  name?: string
}

/**
 * Compute the loudness envelope of the range (WYSIWYG mix through the export
 * segment graph), scaffold an opaque fragment over the range and bake the
 * envelope + style into its TSX. Returns the clip (selected, live preview in
 * the iframe overlay) and the entry file for further hand/Claude tuning.
 */
export async function neonWave(opts: NeonWaveOpts) {
  const st = () => useEditor.getState()
  const project = st().project
  const { start, end } = opts.range
  if (!(end > start)) throw new Error('empty range')
  const source = opts.source ?? 'mix'
  const filter = source === 'mix' ? undefined : { trackIds: [source.trackId] }
  const segments = collectRangeAudio(project, start, end, filter)
  // the same clamp createFragment applies — the envelope must be one value per composition frame
  const fps = Math.max(60, project.fps)
  const duration = end - start
  const env = await window.kadr.audioEnvelope({ audioSegments: segments, duration, fps })
  // only now scaffold: a failed mix leaves no orphan fragment/clip behind
  const frag = await createFragment({ name: opts.name || 'wave', start, end, transparent: false })
  const style = { ...NEON_WAVE_DEFAULTS, ...(opts.style || {}) }
  await window.kadr.writeTextFile(frag.entry, neonWaveTsx(env, frag.meta, style))
  st().select([frag.clipId])
  let peak = 0
  for (const v of env) if (v > peak) peak = v
  return { clipId: frag.clipId, fragmentId: frag.id, entry: frag.entry, frames: frag.meta.durationInFrames, peak }
}
